name: github to deploy
on: 
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'
  pull_request:
    branches:
      - main
    
jobs:
  test:
    name: deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git pull origin main